############################################
# Kotlin / general baseline
############################################
-keepattributes *Annotation*,Signature,InnerClasses,EnclosingMethod
-keepattributes RuntimeVisibleAnnotations,RuntimeInvisibleAnnotations,RuntimeVisibleParameterAnnotations,RuntimeInvisibleParameterAnnotations

# Kotlin metadata (penting untuk beberapa lib)
-keep class kotlin.Metadata { *; }

# Lebih enak untuk debug stacktrace release (opsional tapi berguna)
-keepattributes SourceFile,LineNumberTable

# Coroutines / atomicfu (sering muncul sebagai warning)
-dontwarn kotlinx.coroutines.**
-dontwarn kotlinx.atomicfu.**

############################################
# kotlinx-serialization (JSON)
############################################
# Keep serializer classes generated by the plugin
-keepclassmembers class **$$serializer { *; }
-keep class kotlinx.serialization.** { *; }
-keepclassmembers class ** {
    @kotlinx.serialization.Serializable *;
}

# Kadang membantu untuk class yang pakai @SerialName di field
-keepclasseswithmembers class ** {
    @kotlinx.serialization.SerialName <fields>;
}

############################################
# Ktor client
############################################
-dontwarn io.ktor.**
-dontwarn io.ktor.client.**
-dontwarn io.ktor.http.**
-dontwarn io.ktor.util.**
-dontwarn io.ktor.utils.io.**

# Jika pakai okHttp engine (umum di Android)
-dontwarn okhttp3.**
-dontwarn okio.**

############################################
# SQLDelight
############################################
# SQLDelight runtime biasanya aman, tapi ini menghindari warning pada beberapa setup
-dontwarn com.squareup.sqldelight.**
-keep class com.squareup.sqldelight.** { *; }

# Keep generated database / queries (nama package akan mengikuti project kamu).
# Ini "safety net" supaya class generated tidak ke-strip.
-keep class **Database** { *; }
-keep class **Queries** { *; }

############################################
# Compose
############################################
# Umumnya tidak butuh rule khusus; R8 sudah ngerti Compose.
# Tapi jangan strip Compose runtime (safety, biasanya tidak diperlukan)
-dontwarn androidx.compose.**
-dontwarn org.jetbrains.compose.**

############################################
# Koin (DI)
############################################
# Koin sering pakai reflection (terutama jika kamu pakai parameter injection / named, dll).
-dontwarn org.koin.**
-keep class org.koin.** { *; }

############################################
# Jika kamu pakai reflection untuk class milikmu sendiri,
# kamu mungkin perlu keep package tertentu.
# Contoh (GANTI com.your.package):
-keep class my.lokalan.posq.** { *; }
############################################