# URL
#stagingUrl=http://192.168.100.105:3306/api/
#stagingUrl=http://192.168.18.18:3306/api/
#stagingUrl=http://192.168.0.104:3306/api/
stagingUrl=http://192.168.10.62:3306/api/
productionUrl=https://testing.app/

# Kotzilla
kotzillaStagingKey=ktz-sdk-EanQtGCvM1DrT4K-WrciCdB2m1ARXfBMCmF4KYkH4NM
kotzillaProductionKey=ktz-sdk-kDegrpyGiQux5D3ZEAG3ADs_0kzwzPzLvwyMS-kL-eU
