# URL
stagingUrl=http://192.168.101.5:8000/
productionUrl=https://talangraga-umroh-fastapi-staging.up.railway.app/

# Kotzilla
kotzillaStagingKey=ktz-sdk-EanQtGCvM1DrT4K-WrciCdB2m1ARXfBMCmF4KYkH4NM
kotzillaProductionKey=ktz-sdk-kDegrpyGiQux5D3ZEAG3ADs_0kzwzPzLvwyMS-kL-eU
